server:
  port: 50101 #服务端口
spring:
  application:
    name: xc-govern-center #指定服务名
eureka:
  client:
    register-with-eureka: false #注册服务，是否将自己注册到Eureka服务中
    fetch-registry: false #服务发现，是否从Eureka中获取注册信息
    service-url:  #Eureka客户端与Eureka服务端的交互地址，高科用状态配置对方的地址，单机状态配置自己（如果不配置默认本机）
      dedaultZone: http://localhost:50101/eureka/
  server:
    enable-self-preservation: false #是否开启自我保护模式
    eviction-interval-timer-in-ms: 60000 #服务注册表清理间隔（单位毫秒，默认是60*1000）